# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

House.destroy_all
Character.destroy_all

arryn = House.create(name: "Arryn", sigil_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/1/15/House-Arryn-Main-Shield.PNG/revision/latest?cb=20170101094153", words: "As High as Honor")
frey = House.create(name: "Frey", sigil_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/e/e6/House-Frey-Main-Shield.PNG/revision/latest?cb=20160312124244", words: "We Stand Together")
greyjoy = House.create(name: "Greyjoy", sigil_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/8/86/House-Greyjoy-Main-Shield.PNG/revision/latest?cb=20160312122204", words: "We Do Not Sow")
lannister = House.create(name: "Lannister", sigil_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/8/8a/House-Lannister-Main-Shield.PNG/revision/latest?cb=20170101095357", words: "Hear Me Roar")
stark = House.create(name: "Stark", sigil_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/8/8a/House-Stark-Main-Shield.PNG/revision/latest?cb=20170101103142", words: "Winter is Coming")
tyrell = House.create(name: "Tyrell", sigil_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/c/cf/House-Tyrell-Main-Shield.PNG/revision/latest?cb=20170108163035", words: "Growing Strong")
targaryen = House.create(name: "Targaryen", sigil_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/4/43/House-Targaryen-Main-Shield.PNG/revision/latest?cb=20161206005534", words: "Fire and Blood")
tully = House.create(name: "Tully", sigil_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/b/bd/House-Tully-Main-Shield.PNG/revision/latest?cb=20160312103126", words: "Family, Duty, Honor")
baratheon = House.create(name: "Baratheon", sigil_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/0/00/House-Baratheon-Main-Shield.PNG/revision/latest?cb=20161206005433", words: "Ours is the Fury")
martell = House.create(name: "Martell", sigil_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/7/7e/House-Martell-Main-Shield.PNG/revision/latest?cb=20160312085543", words: "Unbowed, Unbent, Unbroken")
bolton = House.create(name: "Bolton", sigil_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/d/dd/House-Bolton-Main-Shield.PNG/revision/latest?cb=20161231131431", words: "Our Blades Are Sharp")
watch = House.create(name: "The Night's Watch", sigil_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/e/ed/Night%27s-Watch-Main-Shield.PNG/revision/latest?cb=20161231113156", words: "The Sword in the Darkness")

lysa = arryn.characters.create(name: "Lysa Tully", gender: "female", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/4/46/LysaArryn.png/revision/latest?cb=20140523133128", status: "deceased")
robin = arryn.characters.create(name: "Robin Arryn", gender: "male", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/7/74/Robin_Aaryn_Book_of_Stranger.jpg/revision/latest?cb=20160714005525", status: "alive")
walder = frey.characters.create(name: "Walder Frey", gender: "male", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/e/e4/S06E06_-_Walder_Frey_Cropped_new.jpg/revision/latest?cb=20161215025257", status: "deceased")
balon = greyjoy.characters.create(name: "Balon Greyjoy", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/2/27/Balon_Season_6.jpg/revision/latest?cb=20160211221219", status: "deceased")
euron = greyjoy.characters.create(name: "Euron Greyjoy", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/4/4d/Game-of-thrones-6x5_euron_promo..jpg/revision/latest?cb=20160523192637", status: "alive")
yara = greyjoy.characters.create(name: "Yara Greyjoy", gender: "female", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/a/a8/Game_of_thrones_6x5_yara_promo.jpg/revision/latest?cb=20160808022737", status: "alive")
theon = greyjoy.characters.create(name: "Theon Greyjoy", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/6/65/605_Theon_Promo_new.jpg/revision/latest?cb=20160708203536", status: "alive")
tywin = lannister.characters.create(name: "Tywin Lannister", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/7/71/Tywin_Lannister_4x08.jpg/revision/latest?cb=20161215024806", status: "deceased")
cersei = lannister.characters.create(name: "Cersei Lannister", gender: "female", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/c/c7/Queen_Cersei_Main_The_winds_of_Winter.jpg/revision/latest?cb=20161215024728", status: "alive")
jaime = lannister.characters.create(name: "Jaime Lannister", gender: "male", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/c/c5/Jaime_s6_Ep08_.jpg/revision/latest?cb=20161215030911", status: "alive")
tyrion = lannister.characters.create(name: "Tyrion Lannister", gender: "male", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/9/9d/Tyrion6x082.png/revision/latest?cb=20160609061404", status: "alive")
catelyn = stark.characters.create(name: "Catelyn Stark", gender: "female", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/d/d8/CatelynS3Promo.jpg/revision/latest?cb=20131004004734", status: "deceased")
ned = stark.characters.create(name: "Eddard 'Ned' Stark", gender: "male", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/3/37/Eddard_Stark_infobox_new.jpg/revision/latest?cb=20160730050722", status: "deceased")
robb = stark.characters.create(name: "Robb Stark", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/5/50/S3E9_Robb_Stark_main.jpg/revision/latest?cb=20160718071203", status: "deceased")
sansa = stark.characters.create(name: "Sansa Stark", gender: "female", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/6/68/Sansa_stark_s6_battle_bastards_infobox.jpg/revision/latest?cb=20160807084759", status: "alive")
arya = stark.characters.create(name: "Arya Stark", gender: "female", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/a/ad/Arya6x10.png/revision/latest?cb=20160629211505", status: "alive")
bran = stark.characters.create(name: "Brandon Stark", gender: "male", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/7/7b/Bran-0.jpeg/revision/latest?cb=20170105121843", status: "alive")
rickon = stark.characters.create(name: "Rickon Stark", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/d/d9/Battle_of_the_Bastards_42.jpg/revision/latest?cb=20160621185459", status: "deceased")
olenna = tyrell.characters.create(name: "Olenna Tyrell", gender: "female", img_url: "http://gameofthrones.wikia.com/wiki/Olenna_Tyrell", status: "alive")
mace = tyrell.characters.create(name: "Mace Tyrell", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/e/e2/MaceTyrell-Profile.PNG/revision/latest?cb=20160719041706", status: "deceased")
margaery = tyrell.characters.create(name: "Margaery Tyrell", gender: "female", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/b/b5/Margaery_Tyrell_S6.png/revision/latest?cb=20160729224605", status: "deceased")
loras = tyrell.characters.create(name: "Loras Tyrell", gender: "male", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/a/a7/LorasHD3x06-0.png/revision/latest?cb=20150519170126", status: "deceased")
daenerys = targaryen.characters.create(name: "Daenerys Targaryen", gender: "female", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/8/88/Daenerys-0.jpg/revision/latest?cb=20170106122450", status: "alive")
viserys = targaryen.characters.create(name: "Viserys Targaryen", gender: "male", img_url: "http://gameofthrones.wikia.com/wiki/Viserys_Targaryen", status: "deceased")
edmure = tully.characters.create(name: "Edmure Tully", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/b/b6/Edmure_Tully_Season_6.jpg/revision/latest?cb=20160531175620", status: "alive")
brynden = tully.characters.create(name: "Brynden 'the Blackfish' Tully", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/6/61/6x07_Blackfish.png/revision/latest?cb=20160601191023", status: "deceased")
doran = martell.characters.create(name: "Doran Martell", gender: "male", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/a/a5/Doran_Martell_The_Red_Woman.PNG/revision/latest?cb=20161215025119", status: "deceased")
oberyn = martell.characters.create(name: "Oberyn Martell", gender: "male", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/9/96/Oberyn-Martell-house-martell-37118334-2832-4256.jpg/revision/latest?cb=20150815065729", status: "deceased")
robert = baratheon.characters.create(name: "Robert Baratheon", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/d/d4/RobertBaratheon.jpg/revision/latest?cb=20141119000127", status: "deceased")
stannis = baratheon.characters.create(name: "Stannis 'the Mannis' Baratheon", gender: "male", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/7/7a/Stannis_S05E09.png/revision/latest?cb=20161215025402", status: "deceased")
selyse = baratheon.characters.create(name: "Selyse Baratheon", gender: "female", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/6/65/SelyseS05E05.png/revision/latest?cb=20150515051443", status: "deceased")
renly = baratheon.characters.create(name: "Renly Baratheon", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/3/3d/Renly_profile.jpg/revision/latest?cb=20130116113034", status: "deceased")
joffrey = baratheon.characters.create(name: "Joffrey Baratheon", gender: "male", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/e/ea/Joff_promo_shot_infobox_image.jpg/revision/latest?cb=20160809044359", status: "deceased")
myrcella = baratheon.characters.create(name: "Myrcella Baratheon", gender: "female", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/0/02/MyrcellaS5Cropped.jpg/revision/latest?cb=20160802025401", status: "deceased")
tommen = baratheon.characters.create(name: "Tommen Baratheon", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/7/7c/Tommen_blood_of_my_blood.jpg/revision/latest?cb=20160530234845", status: "deceased")
shireen = baratheon.characters.create(name: "Shireen Baratheon", gender: "female", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/e/eb/Shireen_Baratheon_Season_4_profile.jpg/revision/latest?cb=20161215030938", status: "deceased")
roose = bolton.characters.create(name: "Roose Bolton", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/c/c8/Roose-S6-Profile.jpg/revision/latest?cb=20160801075614", status: "deceased")
ramsay = bolton.characters.create(name: "Ramsay Bolton", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/d/d2/Ramsay_S06E09_RESZIED_FOR_INFOBOX.jpg/revision/latest?cb=20160622071734", status: "deceased")
walda = bolton.characters.create(name: "'Fat Walda' Bolton", gender: "female", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/6/65/Walda_and_new_son_s6.jpg/revision/latest?cb=20161215030743", status: "deceased")
jon = watch.characters.create(name: "Jon Snow", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/4/49/Battle_of_the_Bastards_08.jpg/revision/latest?cb=20160615184845", status: "alive")
sam = watch.characters.create(name: "Samwell Tarly", gender: "male", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/5/5c/SamwellTarly-Profile.jpg/revision/latest?cb=20161215025531", status: "alive")
benjen = watch.characters.create(name: "Benjen Stark", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/0/0f/610_Benjen_Promo_Crop.png/revision/latest?cb=20160629183134", status: "undead")
aemon = watch.characters.create(name: "Maester Aemon Targaryen", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/3/32/Aemonepisode5.png/revision/latest?cb=20150511170352", status: "deceased")
alliser = watch.characters.create(name: "Alliser Thorne", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/1/16/Game-of-thrones-season-6-owen-teale.jpeg/revision/latest?cb=20160711235109", status: "deceased")
grenn = watch.characters.create(name: "Grenn", gender: "male", img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/6/6f/Grenn-Profile-HD.jpg/revision/latest?cb=20160712080907", status: "deceased")
pypar = watch.characters.create(name: "Pypar", gender: "male", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/e/e6/Pypar-mockingbird.jpg/revision/latest?cb=20161215025708", status: "deceased")
olly = watch.characters.create(name: "Olly", gender: "male", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/5/51/602_Olly_Promo_Crop.png/revision/latest?cb=20160708062640", status: "deceased")
